openapi: 3.0.2
$ref: common-openapi.yaml
paths:
  $ref: community-openapi.yaml#/paths
  /api/register:
    $ref: spec/paths/api@register.yaml
  /api/firewall/rules:
    $ref: spec/paths/firewall/api@firewall@rules.yaml
  '/api/firewall/rules/{id}':
    $ref: spec/paths/firewall/api@firewall@rules@{id}.yaml
  '/api/firewall/rules/{id}/tags':
    $ref: spec/paths/firewall/api@firewall@rules@{id}@tags.yaml
  '/api/sessions/{uid}/play':
    $ref: spec/paths/sessions/api@sessions@{uid}@play.yaml
  /api/user/resend_email:
    $ref: spec/paths/user/api@user@resend_email.yaml
  '/api/user/{uid}/update_password':
    $ref: spec/paths/user/api@user@{uid}@update_password.yaml
  /api/user/validation_account:
    $ref: spec/paths/user/api@user@validation_account.yaml
  /api/user/recover_password:
    $ref: spec/paths/user/api@user@recover_password.yaml