openapi: 3.0.2
$ref: common-openapi.yaml
tags:
  - name: devices
    description: >
      Routes related to device resources.
      
      
      From that routes, you can act on devices, such as getting a list of them, a single one, update its data or delete 
      it.
      
      
      On that route, you can also create a tag adding it to a device, within a limit of **three tags** per device, 
      update all tags of a device or delete all items.
  - name: tag
    description: Routes related to tag resources.
paths:
  /api/login:
    $ref: spec/paths/api@login.yaml
  /api/devices/auth:
    $ref: spec/paths/devices/api@devices@auth.yaml
  '/api/devices/{uid}/accept':
    $ref: spec/paths/devices/api@devices@{uid}@accept.yaml
  /api/devices:
    $ref: spec/paths/devices/api@devices.yaml
  '/api/devices/{uid}':
    $ref: spec/paths/devices/api@devices@{uid}.yaml
  '/api/devices/{uid}/{status}':
    $ref: spec/paths/devices/api@devices@{uid}@{status}.yaml
  '/api/devices/{uid}/tags':
    $ref: spec/paths/devices/api@devices@{uid}@tags.yaml
  '/api/devices/{uid}/tags/{name}':
    $ref: spec/paths/devices/api@devices@{uid}@tags@{name}.yaml
  /api/auth/user:
    $ref: spec/paths/auth/api@auth@user.yaml
  /api/auth/device:
    $ref: spec/paths/auth/api@auth@device.yaml
  /api/auth/ssh:
    $ref: spec/paths/auth/api@auth@ssh.yaml
  '/api/auth/token/{tenant}':
    $ref: spec/paths/auth/api@auth@token@{tenant}.yaml
  /api/sessions:
    $ref: spec/paths/sessions/api@sessions.yaml
  '/api/sessions/{uid}':
    $ref: spec/paths/sessions/api@sessions@{uid}.yaml
  /api/sshkeys/public-keys:
    $ref: spec/paths/sshkeys/api@sshkeys@public-keys.yaml
  '/api/sshkeys/public-keys/{fingerprint}':
    $ref: spec/paths/sshkeys/api@sshkeys@public-keys@{fingerprint}.yaml
  '/api/sshkeys/public-keys/{fingerprint}/tags':
    $ref: spec/paths/sshkeys/api@sshkeys@public-keys@{fingerprint}@tags.yaml
  '/api/sshkeys/public-keys/{fingerprint}/tags/{name}':
    $ref: spec/paths/sshkeys/api@sshkeys@public-keys@{fingerprint}@tags@{name}.yaml
  '/api/tags':
    $ref: spec/paths/tags/api@tags.yaml
  '/api/tags/{name}':
    $ref: spec/paths/tags/api@tags@{name}.yaml
  /api/namespaces:
    $ref: spec/paths/namespaces/api@namespaces.yaml
  '/api/namespaces/{tenant}':
    $ref: spec/paths/namespaces/api@namespaces@{tenant}.yaml
  '/api/namespaces/{tenant}/members':
    $ref: spec/paths/namespaces/api@namespaces@{tenant}@members.yaml
  '/api/namespaces/{tenant}/members/{uid}':
    $ref: spec/paths/namespaces/api@namespaces@{tenant}@members@{uid}.yaml
  '/api/token/{tenant}':
    $ref: spec/paths/token/api@token@{tenant}.yaml
  '/api/users/{id}/data':
    $ref: spec/paths/users/api@users@{id}@data.yaml
  '/api/users/{id}/password':
    $ref: spec/paths/users/api@users@{id}@password.yaml
  '/api/users/security/{id}':
    $ref: spec/paths/users/api@users@security@{id}.yaml
  /api/users/security:
    $ref: spec/paths/users/api@users@security.yaml
  /api/stats:
    $ref: spec/paths/api@stats.yaml
